package models

import "gorm.io/gorm"

// SeedAdditionalCompanies 追加の企業データをシード（20社以上の多様な企業）
func SeedAdditionalCompanies(db *gorm.DB) error {
	// 既存の企業数を確認
	var count int64
	db.Model(&Company{}).Count(&count)
	if count >= 20 {
		// すでに20社以上存在する場合はスキップ
		return nil
	}

	// 追加企業データ
	companies := []Company{
		{
			Name:             "フィンテックソリューションズ株式会社",
			Description:      "金融業界向けのシステム開発に特化。安定した給与体系と充実した福利厚生。",
			Industry:         "金融・IT",
			EmployeeCount:    500,
			FoundedYear:      2005,
			Location:         "東京都中央区",
			WebsiteURL:       "https://fintech-solutions.example.com",
			Culture:          "堅実で安定志向。コンプライアンスを重視し、長期的なキャリア形成が可能。",
			WorkStyle:        "オフィス勤務",
			TechStack:        `["Java", "Spring Boot", "PostgreSQL", "Kafka", "AWS"]`,
			DevelopmentStyle: "ウォーターフォール",
			MainBusiness:     "金融システム開発、データ分析",
			AverageAge:       36.0,
			FemaleRatio:      30.0,
			IsActive:         true,
			IsVerified:       true,
		},
		{
			Name:             "モバイルアプリ開発株式会社",
			Description:      "スマートフォンアプリ開発に特化したベンチャー企業。成長意欲の高いメンバーが集う。",
			Industry:         "IT・モバイル",
			EmployeeCount:    120,
			FoundedYear:      2016,
			Location:         "東京都品川区",
			WebsiteURL:       "https://mobile-dev.example.com",
			Culture:          "挑戦を奨励し、失敗から学ぶ文化。フラットな組織で年齢に関係なく意見を言える。",
			WorkStyle:        "ハイブリッド（週2日出社）",
			TechStack:        `["Swift", "Kotlin", "Flutter", "Firebase", "GCP"]`,
			DevelopmentStyle: "アジャイル",
			MainBusiness:     "iOS/Androidアプリ開発、モバイルゲーム開発",
			AverageAge:       30.5,
			FemaleRatio:      35.0,
			IsActive:         true,
			IsVerified:       true,
		},
		{
			Name:             "データアナリティクス株式会社",
			Description:      "ビッグデータ分析とAI技術で企業の意思決定を支援。技術力の高いエンジニアが集う。",
			Industry:         "IT・データ分析",
			EmployeeCount:    200,
			FoundedYear:      2012,
			Location:         "東京都渋谷区",
			WebsiteURL:       "https://data-analytics.example.com",
			Culture:          "データドリブンな意思決定。技術的な議論が活発で学習環境が整っている。",
			WorkStyle:        "フルリモート可",
			TechStack:        `["Python", "TensorFlow", "Spark", "Hadoop", "AWS"]`,
			DevelopmentStyle: "アジャイル",
			MainBusiness:     "データ分析、機械学習モデル開発、BIツール提供",
			AverageAge:       33.0,
			FemaleRatio:      28.0,
			IsActive:         true,
			IsVerified:       true,
		},
		{
			Name:             "クラウドインフラ株式会社",
			Description:      "クラウドインフラ構築と運用に特化。安定した技術力と高収入が魅力。",
			Industry:         "IT・インフラ",
			EmployeeCount:    300,
			FoundedYear:      2010,
			Location:         "東京都新宿区",
			WebsiteURL:       "https://cloud-infra.example.com",
			Culture:          "技術の深掘りを評価。24/7サポート体制でオンコール対応あり。",
			WorkStyle:        "ハイブリッド（週3日出社）",
			TechStack:        `["AWS", "Azure", "Kubernetes", "Terraform", "Ansible"]`,
			DevelopmentStyle: "DevOps",
			MainBusiness:     "クラウド移行支援、インフラ運用、SRE支援",
			AverageAge:       34.5,
			FemaleRatio:      20.0,
			IsActive:         true,
			IsVerified:       true,
		},
		{
			Name:             "Eコマースシステムズ株式会社",
			Description:      "ECサイト構築と運用に特化。顧客志向のサービス開発を重視。",
			Industry:         "IT・EC",
			EmployeeCount:    250,
			FoundedYear:      2014,
			Location:         "東京都目黒区",
			WebsiteURL:       "https://ecommerce-systems.example.com",
			Culture:          "顧客第一主義。スピード感のある開発とユーザーフィードバックを重視。",
			WorkStyle:        "ハイブリッド（週2日出社）",
			TechStack:        `["Ruby", "Rails", "Vue.js", "PostgreSQL", "Redis"]`,
			DevelopmentStyle: "アジャイル",
			MainBusiness:     "ECサイト構築、マーケティングツール開発、決済システム",
			AverageAge:       31.0,
			FemaleRatio:      38.0,
			IsActive:         true,
			IsVerified:       true,
		},
		{
			Name:             "ゲーム開発スタジオ株式会社",
			Description:      "オンラインゲームの企画・開発・運営を行う。クリエイティブな環境。",
			Industry:         "IT・ゲーム",
			EmployeeCount:    180,
			FoundedYear:      2011,
			Location:         "東京都世田谷区",
			WebsiteURL:       "https://game-studio.example.com",
			Culture:          "ゲーム好きが集まる環境。創造性を最大限発揮でき、自由な服装・髪型OK。",
			WorkStyle:        "フレックス",
			TechStack:        `["Unity", "C#", "C++", "AWS", "MongoDB"]`,
			DevelopmentStyle: "アジャイル",
			MainBusiness:     "オンラインゲーム開発、運営、ゲームエンジン開発",
			AverageAge:       28.5,
			FemaleRatio:      32.0,
			IsActive:         true,
			IsVerified:       true,
		},
		{
			Name:             "セキュリティソリューションズ株式会社",
			Description:      "サイバーセキュリティ対策のスペシャリスト集団。高度な技術力が求められる。",
			Industry:         "IT・セキュリティ",
			EmployeeCount:    150,
			FoundedYear:      2013,
			Location:         "東京都港区",
			WebsiteURL:       "https://security-solutions.example.com",
			Culture:          "セキュリティ意識が高く、常に最新技術をキャッチアップ。資格取得支援あり。",
			WorkStyle:        "ハイブリッド（週2日出社）",
			TechStack:        `["Python", "Go", "Rust", "Kubernetes", "AWS"]`,
			DevelopmentStyle: "アジャイル",
			MainBusiness:     "セキュリティ診断、脆弱性対策、セキュリティコンサルティング",
			AverageAge:       32.0,
			FemaleRatio:      22.0,
			IsActive:         true,
			IsVerified:       true,
		},
		{
			Name:             "株式会社エデュテックラボ",
			Description:      "教育×テクノロジーで学びの未来を創造。社会貢献性の高いサービスを展開。",
			Industry:         "IT・EdTech",
			EmployeeCount:    90,
			FoundedYear:      2017,
			Location:         "東京都文京区",
			WebsiteURL:       "https://edutech-lab.example.com",
			Culture:          "教育への情熱を持つメンバーが集う。ユーザー（生徒・教師）の声を大切にする文化。",
			WorkStyle:        "フルリモート可",
			TechStack:        `["React", "Node.js", "TypeScript", "PostgreSQL", "AWS"]`,
			DevelopmentStyle: "アジャイル",
			MainBusiness:     "オンライン学習プラットフォーム、教育コンテンツ開発",
			AverageAge:       30.0,
			FemaleRatio:      42.0,
			IsActive:         true,
			IsVerified:       true,
		},
		{
			Name:             "ヘルスケアテクノロジーズ株式会社",
			Description:      "医療×ITで健康寿命の延伸に貢献。最先端のヘルステック企業。",
			Industry:         "IT・ヘルスケア",
			EmployeeCount:    220,
			FoundedYear:      2014,
			Location:         "東京都千代田区",
			WebsiteURL:       "https://healthcare-tech.example.com",
			Culture:          "人の健康を支えるミッション。医療従事者と連携し、社会課題解決に取り組む。",
			WorkStyle:        "ハイブリッド（週2日出社）",
			TechStack:        `["Python", "Django", "Vue.js", "PostgreSQL", "AWS"]`,
			DevelopmentStyle: "アジャイル",
			MainBusiness:     "電子カルテシステム、遠隔医療プラットフォーム、健康管理アプリ",
			AverageAge:       33.5,
			FemaleRatio:      40.0,
			IsActive:         true,
			IsVerified:       true,
		},
		{
			Name:             "グローバルソフトウェア株式会社",
			Description:      "海外展開に積極的な総合IT企業。英語力を活かせる環境。",
			Industry:         "IT・ソフトウェア",
			EmployeeCount:    600,
			FoundedYear:      2008,
			Location:         "東京都港区",
			WebsiteURL:       "https://global-software.example.com",
			Culture:          "多国籍なメンバー構成。英語が公用語で、グローバルなキャリアパスあり。",
			WorkStyle:        "ハイブリッド（週3日出社）",
			TechStack:        `["Java", "Python", "React", "AWS", "Azure", "Docker"]`,
			DevelopmentStyle: "アジャイル",
			MainBusiness:     "グローバルSaaS開発、多言語対応システム、海外進出支援",
			AverageAge:       34.0,
			FemaleRatio:      33.0,
			IsActive:         true,
			IsVerified:       true,
		},
		{
			Name:             "株式会社スマートシティソリューションズ",
			Description:      "IoT・AI技術でスマートシティ実現を目指す次世代型企業。",
			Industry:         "IT・IoT",
			EmployeeCount:    180,
			FoundedYear:      2016,
			Location:         "神奈川県横浜市",
			WebsiteURL:       "https://smartcity-solutions.example.com",
			Culture:          "社会インフラに関わる重要なプロジェクト。技術で地域課題を解決する使命感。",
			WorkStyle:        "ハイブリッド（週2日出社）",
			TechStack:        `["Python", "Go", "React", "PostgreSQL", "AWS IoT", "TensorFlow"]`,
			DevelopmentStyle: "アジャイル",
			MainBusiness:     "IoTプラットフォーム、スマートシティソリューション、データ分析",
			AverageAge:       31.5,
			FemaleRatio:      27.0,
			IsActive:         true,
			IsVerified:       true,
		},
		{
			Name:             "ブロックチェーンテクノロジーズ株式会社",
			Description:      "ブロックチェーン技術で新しい経済圏を創造。最先端技術に挑戦。",
			Industry:         "IT・ブロックチェーン",
			EmployeeCount:    110,
			FoundedYear:      2018,
			Location:         "東京都渋谷区",
			WebsiteURL:       "https://blockchain-tech.example.com",
			Culture:          "先進的な技術への探求心。暗号資産・Web3.0に興味がある人材が集う。",
			WorkStyle:        "フルリモート可",
			TechStack:        `["Solidity", "Rust", "TypeScript", "React", "Node.js", "Ethereum"]`,
			DevelopmentStyle: "アジャイル",
			MainBusiness:     "ブロックチェーン開発、NFTマーケットプレイス、DApps開発",
			AverageAge:       29.0,
			FemaleRatio:      18.0,
			IsActive:         true,
			IsVerified:       true,
		},
		{
			Name:             "株式会社AIロボティクス",
			Description:      "AI×ロボット技術で製造業・物流業の自動化を推進。",
			Industry:         "IT・ロボティクス",
			EmployeeCount:    260,
			FoundedYear:      2010,
			Location:         "神奈川県川崎市",
			WebsiteURL:       "https://ai-robotics.example.com",
			Culture:          "ハードウェアとソフトウェアの融合。実機を触りながら開発できる環境。",
			WorkStyle:        "オフィス勤務（実機開発のため）",
			TechStack:        `["C++", "Python", "ROS", "TensorFlow", "OpenCV"]`,
			DevelopmentStyle: "ウォーターフォール",
			MainBusiness:     "産業用ロボット開発、AI制御システム、物流自動化",
			AverageAge:       35.5,
			FemaleRatio:      15.0,
			IsActive:         true,
			IsVerified:       true,
		},
		{
			Name:             "メディアプラットフォーム株式会社",
			Description:      "動画配信・音楽ストリーミングサービスを展開。エンタメ業界のIT企業。",
			Industry:         "IT・メディア",
			EmployeeCount:    350,
			FoundedYear:      2012,
			Location:         "東京都港区",
			WebsiteURL:       "https://media-platform.example.com",
			Culture:          "エンタメ好きが集まる職場。ユーザーに感動を届ける文化。",
			WorkStyle:        "ハイブリッド（週2日出社）",
			TechStack:        `["Go", "React", "TypeScript", "AWS", "Redis", "Kafka"]`,
			DevelopmentStyle: "アジャイル",
			MainBusiness:     "動画配信サービス、音楽ストリーミング、コンテンツ推薦エンジン",
			AverageAge:       31.0,
			FemaleRatio:      38.0,
			IsActive:         true,
			IsVerified:       true,
		},
		{
			Name:             "株式会社マーケティングオートメーション",
			Description:      "マーケティング支援SaaSを提供。急成長中のスタートアップ。",
			Industry:         "IT・マーケティングテック",
			EmployeeCount:    140,
			FoundedYear:      2017,
			Location:         "東京都目黒区",
			WebsiteURL:       "https://marketing-automation.example.com",
			Culture:          "データドリブンな意思決定。顧客の成功を第一に考えるカスタマーサクセス文化。",
			WorkStyle:        "フルリモート可",
			TechStack:        `["Ruby", "Rails", "React", "PostgreSQL", "AWS", "Redshift"]`,
			DevelopmentStyle: "アジャイル",
			MainBusiness:     "マーケティングオートメーションツール、CRM、データ分析",
			AverageAge:       30.5,
			FemaleRatio:      35.0,
			IsActive:         true,
			IsVerified:       true,
		},
		{
			Name:             "量子コンピューティング研究所株式会社",
			Description:      "量子コンピュータの研究開発を行う最先端テック企業。博士号保持者多数。",
			Industry:         "IT・量子コンピューティング",
			EmployeeCount:    70,
			FoundedYear:      2019,
			Location:         "東京都文京区",
			WebsiteURL:       "https://quantum-computing.example.com",
			Culture:          "学術的な環境。論文執筆・学会発表を奨励。研究開発に集中できる。",
			WorkStyle:        "オフィス勤務（研究設備あり）",
			TechStack:        `["Python", "C++", "Qiskit", "Cirq", "Julia"]`,
			DevelopmentStyle: "研究開発型",
			MainBusiness:     "量子アルゴリズム開発、量子ソフトウェア、研究受託",
			AverageAge:       36.0,
			FemaleRatio:      25.0,
			IsActive:         true,
			IsVerified:       true,
		},
		{
			Name:             "株式会社アグリテック",
			Description:      "農業×テクノロジーで食の未来を創る。社会課題解決型ベンチャー。",
			Industry:         "IT・アグリテック",
			EmployeeCount:    95,
			FoundedYear:      2016,
			Location:         "千葉県柏市",
			WebsiteURL:       "https://agritech.example.com",
			Culture:          "農業への情熱。地方創生・持続可能な農業を目指すミッション。",
			WorkStyle:        "ハイブリッド（週1日出社）",
			TechStack:        `["Python", "Django", "Vue.js", "PostgreSQL", "AWS", "IoT"]`,
			DevelopmentStyle: "アジャイル",
			MainBusiness:     "スマート農業システム、農業データ分析、栽培管理アプリ",
			AverageAge:       32.0,
			FemaleRatio:      30.0,
			IsActive:         true,
			IsVerified:       true,
		},
	}

	for _, company := range companies {
		if err := db.Create(&company).Error; err != nil {
			return err
		}
	}

	// 企業プロファイルをシード (ID 4-20)
	profiles := []CompanyWeightProfile{
		{
			CompanyID:             4, // フィンテックソリューションズ
			TechnicalOrientation:  75,
			TeamworkOrientation:   80,
			LeadershipOrientation: 70,
			CreativityOrientation: 45,
			StabilityOrientation:  95,
			GrowthOrientation:     50,
			WorkLifeBalance:       75,
			ChallengeSeeking:      40,
			DetailOrientation:     90,
			CommunicationSkill:    75,
		},
		{
			CompanyID:             5, // モバイルアプリ開発
			TechnicalOrientation:  80,
			TeamworkOrientation:   70,
			LeadershipOrientation: 55,
			CreativityOrientation: 85,
			StabilityOrientation:  35,
			GrowthOrientation:     95,
			WorkLifeBalance:       65,
			ChallengeSeeking:      90,
			DetailOrientation:     60,
			CommunicationSkill:    65,
		},
		{
			CompanyID:             6, // データアナリティクス
			TechnicalOrientation:  95,
			TeamworkOrientation:   65,
			LeadershipOrientation: 60,
			CreativityOrientation: 70,
			StabilityOrientation:  50,
			GrowthOrientation:     85,
			WorkLifeBalance:       70,
			ChallengeSeeking:      75,
			DetailOrientation:     85,
			CommunicationSkill:    60,
		},
		{
			CompanyID:             7, // クラウドインフラ
			TechnicalOrientation:  90,
			TeamworkOrientation:   75,
			LeadershipOrientation: 65,
			CreativityOrientation: 50,
			StabilityOrientation:  80,
			GrowthOrientation:     65,
			WorkLifeBalance:       55,
			ChallengeSeeking:      60,
			DetailOrientation:     95,
			CommunicationSkill:    70,
		},
		{
			CompanyID:             8, // Eコマースシステムズ
			TechnicalOrientation:  70,
			TeamworkOrientation:   85,
			LeadershipOrientation: 60,
			CreativityOrientation: 75,
			StabilityOrientation:  60,
			GrowthOrientation:     80,
			WorkLifeBalance:       80,
			ChallengeSeeking:      70,
			DetailOrientation:     65,
			CommunicationSkill:    85,
		},
		{
			CompanyID:             9, // ゲーム開発スタジオ
			TechnicalOrientation:  85,
			TeamworkOrientation:   80,
			LeadershipOrientation: 50,
			CreativityOrientation: 100,
			StabilityOrientation:  30,
			GrowthOrientation:     75,
			WorkLifeBalance:       60,
			ChallengeSeeking:      95,
			DetailOrientation:     55,
			CommunicationSkill:    75,
		},
		{
			CompanyID:             10, // セキュリティソリューションズ
			TechnicalOrientation:  95,
			TeamworkOrientation:   70,
			LeadershipOrientation: 65,
			CreativityOrientation: 60,
			StabilityOrientation:  70,
			GrowthOrientation:     70,
			WorkLifeBalance:       65,
			ChallengeSeeking:      80,
			DetailOrientation:     95,
			CommunicationSkill:    65,
		},
		{
			CompanyID:             11, // エデュテックラボ
			TechnicalOrientation:  70,
			TeamworkOrientation:   85,
			LeadershipOrientation: 60,
			CreativityOrientation: 80,
			StabilityOrientation:  50,
			GrowthOrientation:     85,
			WorkLifeBalance:       80,
			ChallengeSeeking:      70,
			DetailOrientation:     60,
			CommunicationSkill:    90,
		},
		{
			CompanyID:             12, // ヘルスケアテクノロジーズ
			TechnicalOrientation:  80,
			TeamworkOrientation:   80,
			LeadershipOrientation: 70,
			CreativityOrientation: 70,
			StabilityOrientation:  75,
			GrowthOrientation:     75,
			WorkLifeBalance:       70,
			ChallengeSeeking:      65,
			DetailOrientation:     85,
			CommunicationSkill:    80,
		},
		{
			CompanyID:             13, // グローバルソフトウェア
			TechnicalOrientation:  75,
			TeamworkOrientation:   80,
			LeadershipOrientation: 75,
			CreativityOrientation: 65,
			StabilityOrientation:  70,
			GrowthOrientation:     80,
			WorkLifeBalance:       70,
			ChallengeSeeking:      70,
			DetailOrientation:     75,
			CommunicationSkill:    90,
		},
		{
			CompanyID:             14, // スマートシティソリューションズ
			TechnicalOrientation:  85,
			TeamworkOrientation:   75,
			LeadershipOrientation: 65,
			CreativityOrientation: 75,
			StabilityOrientation:  60,
			GrowthOrientation:     80,
			WorkLifeBalance:       65,
			ChallengeSeeking:      75,
			DetailOrientation:     70,
			CommunicationSkill:    70,
		},
		{
			CompanyID:             15, // ブロックチェーンテクノロジーズ
			TechnicalOrientation:  95,
			TeamworkOrientation:   70,
			LeadershipOrientation: 55,
			CreativityOrientation: 90,
			StabilityOrientation:  30,
			GrowthOrientation:     95,
			WorkLifeBalance:       60,
			ChallengeSeeking:      95,
			DetailOrientation:     65,
			CommunicationSkill:    65,
		},
		{
			CompanyID:             16, // AIロボティクス
			TechnicalOrientation:  90,
			TeamworkOrientation:   75,
			LeadershipOrientation: 70,
			CreativityOrientation: 75,
			StabilityOrientation:  70,
			GrowthOrientation:     70,
			WorkLifeBalance:       60,
			ChallengeSeeking:      75,
			DetailOrientation:     90,
			CommunicationSkill:    70,
		},
		{
			CompanyID:             17, // メディアプラットフォーム
			TechnicalOrientation:  75,
			TeamworkOrientation:   80,
			LeadershipOrientation: 65,
			CreativityOrientation: 85,
			StabilityOrientation:  60,
			GrowthOrientation:     85,
			WorkLifeBalance:       75,
			ChallengeSeeking:      80,
			DetailOrientation:     65,
			CommunicationSkill:    80,
		},
		{
			CompanyID:             18, // マーケティングオートメーション
			TechnicalOrientation:  70,
			TeamworkOrientation:   85,
			LeadershipOrientation: 65,
			CreativityOrientation: 75,
			StabilityOrientation:  55,
			GrowthOrientation:     90,
			WorkLifeBalance:       75,
			ChallengeSeeking:      80,
			DetailOrientation:     70,
			CommunicationSkill:    85,
		},
		{
			CompanyID:             19, // 量子コンピューティング研究所
			TechnicalOrientation:  100,
			TeamworkOrientation:   70,
			LeadershipOrientation: 60,
			CreativityOrientation: 85,
			StabilityOrientation:  60,
			GrowthOrientation:     70,
			WorkLifeBalance:       65,
			ChallengeSeeking:      90,
			DetailOrientation:     95,
			CommunicationSkill:    65,
		},
		{
			CompanyID:             20, // アグリテック
			TechnicalOrientation:  75,
			TeamworkOrientation:   80,
			LeadershipOrientation: 65,
			CreativityOrientation: 80,
			StabilityOrientation:  55,
			GrowthOrientation:     75,
			WorkLifeBalance:       75,
			ChallengeSeeking:      70,
			DetailOrientation:     70,
			CommunicationSkill:    75,
		},
	}

	for _, profile := range profiles {
		if err := db.Create(&profile).Error; err != nil {
			return err
		}
	}

	return nil
}
